/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebButton {
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface WebInput {
        "disabled": boolean;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "type": 'text' | 'number' | 'email' | 'password';
        "value": string | number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebButtonElement extends Components.WebButton, HTMLStencilElement {
    }
    var HTMLWebButtonElement: {
        prototype: HTMLWebButtonElement;
        new (): HTMLWebButtonElement;
    };
    interface HTMLWebInputElement extends Components.WebInput, HTMLStencilElement {
    }
    var HTMLWebInputElement: {
        prototype: HTMLWebInputElement;
        new (): HTMLWebInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "web-button": HTMLWebButtonElement;
        "web-input": HTMLWebInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebButton {
        "disabled"?: boolean;
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface WebInput {
        "disabled"?: boolean;
        "name"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: 'text' | 'number' | 'email' | 'password';
        "value"?: string | number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "web-button": WebButton;
        "web-input": WebInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-button": LocalJSX.WebButton & JSXBase.HTMLAttributes<HTMLWebButtonElement>;
            "web-input": LocalJSX.WebInput & JSXBase.HTMLAttributes<HTMLWebInputElement>;
        }
    }
}
